server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    return 301 https://google.com$request_uri;
}

# Catch-all HTTPS
server {
    listen 443 ssl  default_server;
    listen [::]:443 ssl  default_server;
    server_name _;

    ssl_certificate /etc/nginx/conf.d/ssl/www.domain.local/www.domain.local.crt;
    ssl_certificate_key /etc/nginx/conf.d/ssl/www.domain.local/www.domain.local.key;

    return 301 https://google.com$request_uri;
}
